version: '3'
services:
  service:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    environment:
      NATS_URI: nats://mypc:4222
    network_mode: host
    # ports:
    #   - 8000:8000
    # depends_on:
    #   - nats
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      NATS_URI: nats://mypc:4222
    network_mode: host
    # depends_on:
    #   - nats
  # different_worker:
  #   build: worker
  #   environment:
  #     NATS_URI: nats://host.docker.internal:4222
  #   network_mode: host
  #   # depends_on:
  #   #   - nats
  dlq_worker:
    build:
      context: .
      dockerfile: ./dlq-worker/Dockerfile
    environment:
      NATS_URI: nats://mypc:4222
    network_mode: host
    # depends_on:
    #   - nats
