version: '3'
services:
  service:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    environment:
      NATS_URI: nats://localhost:4222
    network_mode: host
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      NATS_URI: nats://localhost:4222
    network_mode: host
  dlq_worker:
    build:
      context: .
      dockerfile: ./dlq-worker/Dockerfile
    environment:
      NATS_URI: nats://localhost:4222
    network_mode: host
