@endpoint = http://localhost:8000
@job = /job/i47HxSOnL5tOrrt7N8oGJS4VuUzHBl?token=uRksSvJpTo7WXQxs53eBnnnjwgJEat
###
GET {{endpoint}}
###
GET {{endpoint}}/health
###
POST {{endpoint}}/job
Content-Type: application/json

{
    "payload": "asdf"
}
###
GET {{endpoint}}{{job}}