@endpoint = http://localhost:8000
@job = /job/a1UxM5Um2toGhwQfYqUIoDDaJru5EB?token=6Fgr7glu7DerSW62RX1WFitIpdyuqG
###
GET {{endpoint}}
###
GET {{endpoint}}/health
###
POST {{endpoint}}/job
Content-Type: application/json

{
    "payload": "retry"
}
###
GET {{endpoint}}{{job}}